### ISSUE TITLE
Docs not working

### ISSUE THREAD

**Issue by pierreis** [grissius/protocat#25]
It seems that the documentation website is not working (it was earlier today).
Is that expected because of an ongoing maintenance / change or domain, possibly?

Also, thanks a lot for your work on this project. It was clearly missing, and it is great to see some great tooling around Typescript and gRPC 🙂

**Comment by grissius** [comment]
Yes, this is an expected outage due to domain change. I hope it should be resolved by tomorrow. The configuration should be applied in 24-48 hours.

In the meantime feel free to browse the wiki docs in less fancy way in [wiki](https://github.com/grissius/protocat/tree/master/website/docs/wiki), or if you're feeling exquisitly wonderful, you can run the docs for now locally `git clone https://github.com/grissius/protocat && cd protocat/website && npm i && npm run start`.

Sorry for the inconvenience and thank you for reporting. :heart: 

> Also, thanks a lot for your work on this project.

Thanks, I hope it serves you well. :bow:

**Comment by grissius** [comment]
The configuration is probably still pending. I added a temporary link in the readme.
