### ISSUE TITLE
An alternate way to return Errors?

### ISSUE THREAD

**Issue by rrichardson** [grissius/protocat#35]
In our shop we're pretty anti-exceptions. They're basically forbidden. (Our other languages are Rust and Go) So I definitely don't want to make them a required part of the Service control flow. 

I'd like to provide a way to return an error result for certain scenarios.  I think for application-level errors, they could be part of the Service Protocol, but for system-level errors, as well as authz/n errors, I'd like to be able to return the GRPC errors. 
Looking at the relevant parts of [wrap to handler](https://github.com/grissius/protocat/blob/master/src/lib/server/application.ts#L145-L151) it seems the only way to return an error to the client is to throw it. 

One idea I had was to just check for an `error` property of the call at the end of the `wrapToHandler` wrapper. If it is populated, `emit('error', addMeta(err, call))`  

One other option is just add an optional error argument to the middleware callback, and allow the user to register a post-handler function which will return the correct result.   

I'm open to any other ideas.

**Comment by grissius** [comment]
A standard way to propagate errors for Node API is to throw / reject / first item of callback / emit. The native gRPC library is following the conventions using emit for streams and callback for unary response.

ProtoCat promisifies the callbacks, which is a mainstream approach adapted by many libraries to solve the issue with callbacks with progressively improving support for native promises and async await API.

I am against integrating the proposal in said form because:
 1. It is not conventional for Node nor JS APIs. [citation needed]
 2. Being unconventional, it would not be an efficient replacement but would have to coexist with the current error handling IMO,  adding complexity only extreme minority of users would benefit from.
 3. Your proposal is not a well established concept or at least does not seem like one. There is no such behavior AFAIK in Koa ProtoCat is heavily inspired from. It also does not feel like a natural extension of the core grpc API.
 4. The proposal does not work well for streaming RPCs or is not thought out.
 5. I think we should have a stronger argument than private policy.

I am leaving it open for discussion, but I don't personally think that it is a pressing issue. You can (and likely do) use the promise API with async functions avoiding the concept of breaking the execution flow with a Promise container akin to FP-based Either and similar. I don't think replicating the two value return object in custom structure is a reasonable way to go.
